# Generated by Django 2.2.5 on 2019-09-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeDaMusica', models.CharField(max_length=255)),
                ('artista', models.CharField(max_length=255)),
                ('generoMusica', models.CharField(max_length=255)),
                ('linkDaMusica', models.CharField(max_length=255)),
            ],
        ),
    ]
