# Generated by Django 2.2.5 on 2019-09-06 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Musica',
        ),
    ]
