# Generated by Django 2.2.5 on 2019-09-06 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0002_auto_20190906_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musica',
            old_name='generoMusica',
            new_name='generoMusical',
        ),
    ]
